# Generated by Django 4.2.1 on 2023-06-05 12:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='unique_id',
            field=models.CharField(default=users.models.create_unique_appuser_id, max_length=16),
        ),
    ]
