# Generated by Django 4.2.1 on 2023-06-05 12:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='unique_id',
            field=models.CharField(db_index=True, default=users.models.create_unique_appuser_id, max_length=16, unique=True),
        ),
    ]
